framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: warehouse_space

        # Redis configuration
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Namespaced pools for different layers
        pools:
            # Cache pool for domain entities
            cache.domain:
                adapter: cache.app
                default_lifetime: 3600
                
            # Cache pool for application services
            cache.application:
                adapter: cache.app
                default_lifetime: 1800
                
            # Cache pool for integration data
            cache.integration:
                adapter: cache.app
                default_lifetime: 900
                
            # Cache pool for repository queries
            cache.repository:
                adapter: cache.app
                default_lifetime: 600

when@test:
    framework:
        cache:
            app: cache.adapter.filesystem
            default_redis_provider: ~