framework:
    messenger:
        # Enable failure transport for robust message handling
        failure_transport: failed

        transports:
            # Async transport using Redis for better performance
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            
            # Failed messages transport for retry mechanisms
            failed: 'redis://redis:6379/failed_messages'
            
            # Sync transport for immediate processing
            sync: 'sync://'
            
            # High priority transport for critical operations
            high_priority: 'redis://redis:6379/high_priority'

        routing:
            # Default routing for other messages
            '*': async

when@test:
    framework:
        messenger:
            transports:
                # Use in-memory transport for testing
                async: 'in-memory://'
                failed: 'in-memory://'
                high_priority: 'in-memory://'